CREATE TABLE IF NOT EXISTS episode (
    id INTEGER NOT NULL
    , post_id TEXT NOT NULL
    , title TEXT
    , PRIMARY KEY(id, post_id)
    , FOREIGN KEY(id) REFERENCES rewatch(id) ON DELETE RESTRICT ON UPDATE CASCADE
)